@extends('frontend.layouts.master')
@section('content')
@include('frontend.home.divide')
@include('frontend.home.whatwedo')
@include('frontend.home.member')
@include('frontend.home.uni')
@include('frontend.home.activity')
@include('frontend.home.post')
@endsection
